networks:
    web_clients:
        external: true
    kzen-backend-network:
        external: true
services:
    reverse-proxy:
        build: .
        container_name: kvm_nginx_reverse_proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /var/www/letsencrypt:/var/www/letsencrypt
        networks:
            - web_clients
            - kzen-backend-network


