version: '3.8'

services:
    reverse-proxy:
        build: .
        container_name: kvm_nginx_reverse_proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - web_clients
networks:
    web_clients:
        external: true
