networks:
    web_clients:
        external: true
services:
    reverse-proxy:
        build: .
        container_name: kvm_nginx_reverse_proxy
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            # - volumes_from:
                # - kzen-container
                # - ourstory-container
        networks:
            - web_clients
